title: Learn AI Materials on Cognitive Search
description: Microsoft labs for learning how to build AI solutions using Cognitive Search.
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-Cognitive-Search
github: [metadata]
